@extends('layouts.admin')

<style>
    /* Align search bar properly */
    .dataTables_filter {
        text-align: left !important;
    }
    .dataTables_filter input {
        width: 230px !important;
        margin-left: 10px !important;
    }

    /* Align show entries to the right */
    .dataTables_length {
        text-align: right !important;
    }
    .dataTables_length select {
        margin: 0 5px !important;
        width: 70px !important;
        display: inline-block;
    }

    #retailer-orders-table tbody td {
        font-size: 0.85em; /* Decrease font size to view more records */
    }
</style>


@section('page-body')
<div class="container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-6">
                <h3>Distributor Dashboard - Assigned Retailer Orders</h3>
            </div>
            <div class="col-6">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="fa fa-home"></i></a></li>
                    <li class="breadcrumb-item">Distributor</li>
                    <li class="breadcrumb-item active">Assigned Retailer Orders</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            @if(session('success'))
            <div class="alert alert-success">{{ session('success') }}</div>
            @endif

            <div class="table-responsive">
                <table class="display table table-striped table-hover" id="retailer-orders-table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Retailer Name</th>
                            <th>Product Name</th>
                            <th>Quantity</th>
                            <th>Total Amount</th>
                            <th>Status / Actions</th>
                            <th>Field Staff</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection

@push('styles')
    <!-- DataTables with Bootstrap 5 -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.1/css/buttons.bootstrap5.min.css">
@endpush

@push('scripts')
    <!-- jQuery (required) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Bootstrap 5 JS (ensure already included in your layout) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

    <!-- DataTables Bootstrap 5 -->
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>

    <!-- DataTables Buttons -->
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.bootstrap5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.print.min.js"></script>

    <script>
        $(document).ready(function() {
            var table = $('#retailer-orders-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: "{{ route('distributor.orders.index') }}", // This should be the route for distributor's retailer orders
                    type: 'GET'
                },
                columns: [
                    { data: 'id', name: 'id' },
                    { data: 'retailer_name', name: 'retailer_name' },
                    { data: 'product_name', name: 'product_name' },
                    { data: 'quantity', name: 'quantity' },
                    { data: 'total_amount', name: 'total_amount' },
                    {
                        data: null, // Use null to indicate that data will be generated by the render function
                        name: 'status_actions',
                        orderable: false,
                        searchable: false,
                        render: function(data, type, row) {
                            var status = row.status.toLowerCase().replace(/ /g, '_');
                            var output = '';

                            // Logic for displaying status or action buttons
                            if (status === 'pending') {
                                output = `<button class="btn btn-primary btn-sm accept-retailer-order-btn" data-id="${row.id}">Accept</button>`;
                            } else if (status === 'accepted_by_distributor') {
                                var fieldstaffs = {!! json_encode(App\Models\FieldStaff::where('distributor_id', Auth::user()->distributor->id)->with('user')->get()->map(function($fieldstaff) {
                                    return ['id' => $fieldstaff->id, 'name' => $fieldstaff->user->name];
                                })) !!};
                                var options = '<option value="">-- Select Field Staff --</option>';
                                fieldstaffs.forEach(function(fieldstaff) {
                                    options += `<option value="${fieldstaff.id}">${fieldstaff.name}</option>`;
                                });

                                output = `
                                    <form class="assign-fieldstaff-form">
                                        @csrf
                                        <input type="hidden" name="order_id" value="${row.id}">
                                        <div class="input-group">
                                            <select class="form-select" name="fieldstaff_id" required>
                                                ${options}
                                            </select>
                                            <button type="submit" class="btn btn-primary btn-sm">Assign</button>
                                        </div>
                                    </form>
                                `;
                            } else {
                                // Default status display for other states
                                var badgeClass = 'badge-primary';
                                switch (status) {
                                    case 'assigned_to_fieldstaff':
                                        badgeClass = 'badge-info';
                                        break;
                                    case 'out_for_delivery':
                                        badgeClass = 'badge-secondary';
                                        break;
                                    case 'delivered':
                                        badgeClass = 'badge-success';
                                        break;
                                    case 'cancelled':
                                        badgeClass = 'badge-danger';
                                        break;
                                }
                                output = `<span class="badge ${badgeClass}">${row.status}</span>`;
                            }
                            return output;
                        }
                    },
                    { data: 'fieldstaff_name', name: 'fieldstaff_name' },
                ],
                dom:  "<'row mb-3'<'col-sm-12'B>>" + 
                        "<'row mb-3 d-flex align-items-center'<'col-md-6'f><'col-md-6 text-end'l>>" +
                        "rtip",
                buttons: [
                    { extend: 'copy', className: 'btn btn-primary btn-sm' },
                    { extend: 'csv', className: 'btn btn-primary btn-sm' },
                    { extend: 'excel', className: 'btn btn-primary btn-sm' },
                    { extend: 'pdf', className: 'btn btn-primary btn-sm' },
                    { extend: 'print', className: 'btn btn-primary btn-sm' },
                ]
            });

            // Handle Accept Retailer Order button click
            $('#retailer-orders-table').on('click', '.accept-retailer-order-btn', function() {
                var orderId = $(this).data('id');
                if (confirm('Are you sure you want to accept this retailer order?')) {
                    $.ajax({
                        url: `/retailer-orders-management/${orderId}/accept-order`,
                        method: 'POST',
                        data: {
                            _token: '{{ csrf_token() }}'
                        },
                        success: function(response) {
                            if (response.success) {
                                alert(response.success);
                                table.draw(); // Redraw the table
                            } else {
                                alert(response.error || 'Something went wrong.');
                            }
                        },
                        error: function(xhr, status, error) {
                            console.error('Error:', error);
                            alert('An error occurred while accepting the order.');
                        }
                    });
                }
            });

            // Handle Assign Field Staff form submission
            $('#retailer-orders-table').on('submit', '.assign-fieldstaff-form', function(e) {
                e.preventDefault();

                var form = $(this);
                var orderId = form.find('input[name="order_id"]').val();
                var fieldstaffId = form.find('select[name="fieldstaff_id"]').val();
                var token = form.find('input[name="_token"]').val();

                if (!fieldstaffId) {
                    alert('Please select a field staff.');
                    return;
                }

                $.ajax({
                    url: `/retailer-orders-management/${orderId}/assign-fieldstaff`,
                    method: 'POST',
                    data: {
                        _token: token,
                        fieldstaff_id: fieldstaffId
                    },
                    success: function(response) {
                        if (response.success) {
                            alert(response.success);
                            table.draw(); // Redraw the table
                        } else {
                            alert(response.error || 'Something went wrong.');
                        }
                    },
                    error: function(xhr, status, error) {
                        console.error('Error:', error);
                        alert('An error occurred while assigning field staff.');
                    }
                });
            });
        });
    </script>
@endpush