@extends('layouts.admin')

<style>
    /* Align search bar properly */
    .dataTables_filter {
        text-align: left !important;
    }
    .dataTables_filter input {
        width: 230px !important;
        margin-left: 10px !important;
    }

    /* Align show entries to the right */
    .dataTables_length {
        text-align: right !important;
    }
    .dataTables_length select {
        margin: 0 5px !important;
        width: 70px !important;
        display: inline-block;
    }
</style>

@section('page-body')
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5>My Orders</h5>
                </div>
                <div class="card-body">
                    @if(session('success'))
                    <div class="alert alert-success">{{ session('success') }}</div>
                    @endif

                    <div class="table-responsive">
                        <table class="display table table-striped table-hover" id="retailer-orders-table">
                            <thead>
                                <tr>
                                    <th>Order ID</th>
                                    <th>Product</th>
                                    <th>Quantity</th>
                                    <th>Unit Price</th>
                                    <th>Total Amount</th>
                                    <th>Placed At</th>
                                    <th>Status / Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('styles')
    <!-- DataTables with Bootstrap 5 -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.1/css/buttons.bootstrap5.min.css">
@endpush

@push('scripts')
    <!-- DataTables Bootstrap 5 -->
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>

    <!-- DataTables Buttons -->
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.bootstrap5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.print.min.js"></script>

    <script>
        $(document).ready(function() {
            $('#retailer-orders-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: "{{ route('retailer.orders.index') }}",
                    type: 'GET'
                },
                columns: [
                    { data: 'id', name: 'id' },
                    { data: 'product_name', name: 'product_name' },
                    { data: 'quantity', name: 'quantity' },
                    { data: 'unit_price', name: 'unit_price' },
                    { data: 'total_amount', name: 'total_amount' },
                    { data: 'placed_at', name: 'placed_at' },
                    {
                        data: null, // Use null to indicate that data will be generated by the render function
                        name: 'status_actions',
                        orderable: false,
                        searchable: false,
                        render: function(data, type, row) {
                            var status = row.status.toLowerCase();
                            var output = '';
                            var viewUrl = "{{ route('retailer.orders.show', ':id') }}".replace(':id', row.id);

                            switch (status) {
                                case 'pending':
                                    output = `<span class="badge badge-warning">Waiting for confirmation</span>`;
                                    break;
                                case 'accepted':
                                    output = `<span class="badge badge-info">Accepted by Distributor</span>`;
                                    break;
                                case 'dispatched':
                                    output = `<button class="btn btn-success btn-sm confirm-delivery-btn" data-id="${row.id}">Confirm Delivery</button>`;
                                    break;
                                case 'delivered':
                                    output = `<span class="badge badge-success">${row.status}</span>`;
                                    break;
                                case 'cancelled':
                                    output = `<span class="badge badge-danger">${row.status}</span>`;
                                    break;
                                default:
                                    output = `<span class="badge badge-primary">${row.status}</span>`;
                                    break;
                            }
                            // Always show a view button for retailers
                            output += ` <a href="${viewUrl}" class="btn btn-sm btn-info">View</a>`;
                            return output;
                        }
                    }
                ],
                dom: "<'row mb-3'<'col-sm-12'B>>" + 
                        "<'row mb-3 d-flex align-items-center'<'col-md-6'f><'col-md-6 text-end'l>>" +
                        "rtip",
                buttons: [
                    { extend: 'copy', className: 'btn btn-primary btn-sm' },
                    { extend: 'csv', className: 'btn btn-primary btn-sm' },
                    { extend: 'excel', className: 'btn btn-primary btn-sm' },
                    { extend: 'pdf', className: 'btn btn-primary btn-sm' },
                    { extend: 'print', className: 'btn btn-primary btn-sm' },
                ],
                drawCallback: function() {
                    feather.replace();
                }
            });

            // Handle Confirm Delivery button click
            $('#retailer-orders-table').on('click', '.confirm-delivery-btn', function() {
                var orderId = $(this).data('id');
                if (confirm('Are you sure you want to confirm the delivery of this order?')) {
                    $.ajax({
                        url: `/retailer/orders/${orderId}/confirm-delivery`,
                        method: 'POST',
                        data: {
                            _token: '{{ csrf_token() }}'
                        },
                        success: function(response) {
                            if (response.success) {
                                alert(response.success);
                                $('#retailer-orders-table').DataTable().draw(); // Redraw the table
                            } else {
                                alert(response.error || 'Something went wrong.');
                            }
                        },
                        error: function(xhr, status, error) {
                            console.error('Error:', error);
                            alert('An error occurred while confirming the delivery.');
                        }
                    });
                }
            });
        });
    </script>
@endpush
